import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  wikiSidebar: [
    'intro',
    {
      type: 'category',
      label: '成果展示',
      link: {type: 'doc', id: 'achievements/index'},
      items: [{type: 'autogenerated', dirName: 'achievements'}],
    },
    {
      type: 'category',
      label: '学习教程',
      link: {type: 'doc', id: 'tutorials/index'},
      items: [{type: 'autogenerated', dirName: 'tutorials'}],
    },
    {
      type: 'category',
      label: '技术心得',
      link: {type: 'doc', id: 'tech-notes/index'},
      items: [{type: 'autogenerated', dirName: 'tech-notes'}],
    },
    {
      type: 'category',
      label: '团队规范',
      link: {type: 'doc', id: 'standards/index'},
      items: [{type: 'autogenerated', dirName: 'standards'}],
    },
    {
      type: 'category',
      label: '资源汇总',
      link: {type: 'doc', id: 'resources/index'},
      items: [{type: 'autogenerated', dirName: 'resources'}],
    },
    {
      type: 'category',
      label: '工业文档',
      link: {type: 'doc', id: 'industry-docs/index'},
      items: [
        {
          type: 'link',
          label: 'Prompt Engineering——Codebuddy CLI 提示词设计 (完整翻译版)',
          href: '/sage-wiki/docs/industry-docs/prompt-engineering-cb-cli',
        },
      ],
    },
  ],
};

export default sidebars;
